apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-auth-01
  name: api-auth-01
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-auth-01
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-auth-01
    spec:
      containers:
      - image: florinchelaru/api-auth-01
        imagePullPolicy: Always
        name: api-auth-01
        env:
        - name: PORT
          value: "3000"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30