apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-04-04T22:15:12Z"
  generation: 1
  labels:
    app: api-auth-01
  name: api-auth-01
  namespace: default
  resourceVersion: "1018"
  uid: e8f3ec75-aeb3-4e2a-8e1f-d008351409ca
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api-auth-01
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-auth-01
    spec:
      containers:
      - image: florinchelaru/api-auth-01
        imagePullPolicy: Always
        name: api-auth-01
        env:
        - name: PORT
          value: "3000"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-04-04T22:15:12Z"
    lastUpdateTime: "2022-04-04T22:15:55Z"
    message: ReplicaSet "api-auth-01-57d47b644" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-04-04T22:16:28Z"
    lastUpdateTime: "2022-04-04T22:16:28Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
